[package]
name = "terminal_note"
version = "0.1.0"
authors = ["yunfengzhang.zyf <yunfengzhang.zyf@alibaba-inc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eventual = ""
chrono = "0.4.0"
termion = "*"

